[unstable]
# a lot of built-in function come with compiler_builtins
# that we will recompile, but some are assumed to be provided
# by the C library on the system, e.g:
# memcpy, memset, memcmp ...
# we can't link to the C library of the OS as it does not
# exists, so we use a well tested implementation
build-std-features = ["compiler-builtins-mem"]
# allow us to recompile core instead of using the default 
# which is precompiled for supported host triples
# e.g x86_64-unknown-linux-gnu, but not our custom target
# it is unstable so we need a Rust nightly
# compiler_builtins is a dependency
# and we need rust sources to compile,
# which can be added with
# rustup component add rust-src 
build-std = ["core", "compiler_builtins"]

[build]
target = "embedded-rust-os.json"